### ISSUE TITLE
想要高清的mp4

### ISSUE THREAD

**Issue by 5wcx** [adodo1/save-b#1]
如何获得高清的mp4 不通过合并。

**Comment by adodo1** [comment]
> 如何获得高清的mp4 不通过合并。

合并就是原始的MP4

FLV是一种封装格式，你可以百度一下，用FFMPEG转一下，或者用小丸工具箱处理

**Comment by adodo1** [comment]
我做这个项目的目的就是想保护B站的资源

因为发现我收藏的很多UP主的视频都被和谐掉了，非常惋惜，他们的视频非常非常有用

@5wcx
